# Generated by Django 4.2.5 on 2023-09-11 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=150, unique=True)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='ServiceTariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('category', models.IntegerField(choices=[(1, 'IT Park'), (2, 'IT Park'), (3, 'IT Park'), (4, 'IT Park'), (5, 'IT Park')])),
                ('title', models.IntegerField(choices=[(1, 'Бухгалтерский аутсорсинг для резидентов IT Park'), (2, 'Бухгалтерский аутсорсинг для производственных предприятий'), (3, 'Бухгалтерский аутсорсинг для оптовой торговли'), (4, 'Бухгалтерский аутсорсинг для предприятий общепита'), (5, 'Бухгалтерский аутсорсинг для предприятий оказывающие услуги')])),
                ('field1', models.IntegerField(choices=[(1, 'Включено'), (2, 'Не включено')])),
                ('field2', models.IntegerField(choices=[(1, 'Включено'), (2, 'Не включено')])),
                ('field3', models.IntegerField(choices=[(1, 'Включено'), (2, 'Не включено')])),
                ('field4', models.IntegerField(choices=[(1, 'Включено'), (2, 'Не включено')])),
            ],
            options={
                'verbose_name': 'ServiceTariff',
                'verbose_name_plural': 'ServiceTariffs',
                'db_table': 'serviceTariff',
            },
        ),
    ]
